import { ItemView, MarkdownRenderer, Menu, Modal, Notice, setIcon, type App, type WorkspaceLeaf, type ViewStateResult } from "obsidian";
import type VisualAgentMapPlugin from "../../main";
import { CoffeeEngine } from "./engine";
import { CoffeeStorage } from "./storage";
import { copyLegacySession, createSession, type AnyCoffeeSession, type CoffeeSession, type GuestCategory, type GuestCounts, type GuestSettings, type NamedGuest } from "./types";
import { COFFEE_SAMPLE_EN, COFFEE_SAMPLE_ZH } from "./samples";
import { effectiveTableStatus, formatTableTime, selectTables, tableTime, topicTableCount, type TableListFilter, type TableListItem } from "./list";
import { COFFEE_TOPICS, coffeeTopicText, pickCoffeeTopic } from "./topics";

export const COFFEE_TABLES_NAME = "Coffee Tables";
export const COFFEE_TABLES_VIEW_TYPE = "coffee-tables-view";
class CoffeeDeleteModal extends Modal {
  private resolveResult?: (confirmed: boolean) => void;
  private confirmed = false;
  constructor(app: App, private topic: string, private zh: boolean) { super(app); }
  confirm(): Promise<boolean> { return new Promise(resolve => { this.resolveResult = resolve; this.open(); }); }
  onOpen(): void {
    const content = this.contentEl; content.empty(); content.createEl("h2", { text: this.zh ? "刪除這場桌聊？" : "Delete this table?" });
    content.createEl("p", { text: this.zh ? `「${this.topic}」的 Markdown 與設定會先備份，再移入垃圾桶。之後可從「最近刪除」復原。` : `“${this.topic}” will be backed up and moved to the vault trash. You can restore it from Recently deleted.` });
    const buttons = content.createDiv({ cls: "modal-button-container" }); const cancel = buttons.createEl("button", { text: this.zh ? "取消" : "Cancel" }); cancel.onclick = () => this.close(); const remove = buttons.createEl("button", { text: this.zh ? "移到垃圾桶" : "Move to trash" }); remove.addClass("mod-warning"); remove.onclick = () => { this.confirmed = true; this.close(); };
  }
  onClose(): void { this.contentEl.empty(); this.resolveResult?.(this.confirmed); this.resolveResult = undefined; }
}
const CATEGORIES: Array<{ id: GuestCategory; en: string; zh: string; descEn: string; descZh: string }> = [
  { id: "experts", en: "Topic experts", zh: "主題專家", descEn: "Bring subject knowledge and challenge each other’s assumptions.", descZh: "補充專業背景，挑戰彼此的判斷。" },
  { id: "cross-domain", en: "Cross-domain experts", zh: "跨領域專家", descEn: "Offer useful ideas from another field and explain where the analogy breaks.", descZh: "借用其他領域的經驗，也指出類比限制。" },
  { id: "generalist", en: "Curious generalists", zh: "好奇的通才", descEn: "Ask direct questions and connect the discussion to everyday life.", descZh: "問出直白問題，把討論拉回日常。" },
  { id: "affected", en: "Affected perspectives", zh: "受影響者", descEn: "Challenge abstract assumptions from a lived situation.", descZh: "從實際處境出發，挑戰抽象假設。" }
];
export function parseGuests(markdown: string): Array<{ name: string; role: string; bio: string }> {
  return [...markdown.matchAll(/^- \*\*(.+?)\s*[｜|]\s*(.+?)\*\*[：:]\s*(.+)$/gm)].map(match => /主持人|觀察者|專家|藝人|當事人/.test(match[1]) ? { name: match[2].trim(), role: match[1].trim(), bio: match[3].trim() } : { name: match[1].trim(), role: match[2].trim(), bio: match[3].trim() });
}
export function rosterFor(session: CoffeeSession, markdown: string): Array<{ name: string; role: string; bio: string }> {
  const zh = session.language === "zh-TW", settings = session.guests;
  const people = [...new Map(parseGuests(markdown).map(person => [person.name.trim().toLocaleLowerCase(), person])).values()];
  const roles = [{ category: "host", en: "Host", zh: "主持人", count: settings?.hostCount ?? 2 }, { category: "observer", en: "Observer", zh: "觀察者", count: 1 }, ...CATEGORIES.map(item => ({ category: item.id, en: item.en, zh: item.zh, count: settings?.counts[item.id] ?? 0 }))];
  const roleKey = (role: string): string => /主持|host/i.test(role) ? "host" : /觀察|observer/i.test(role) ? "observer" : /跨領域|cross.domain/i.test(role) ? "cross-domain" : /通才|generalist/i.test(role) ? "generalist" : /受影響|當事|affected|lived/i.test(role) ? "affected" : /專家|expert/i.test(role) ? "experts" : "";
  const used = new Map<string, number>(); for (const person of people) { const key = roleKey(person.role); if (key) used.set(key, (used.get(key) ?? 0) + 1); }
  const placeholders = roles.flatMap(item => Array.from({ length: Math.max(0, item.count - (used.get(item.category) ?? 0)) }, (_, index) => ({ name: `${zh ? item.zh : item.en} ${index + 1}`, role: zh ? "即將登場" : "Joining", bio: zh ? "等待人物介紹" : "Waiting for the introduction" })));
  return [...people, ...placeholders];
}
export function liveRosterFor(session: CoffeeSession, draftMarkdown = ""): Array<{ name: string; role: string; bio: string }> {
  const history = [session.transcriptMarkdown, ...(session.rounds ?? []).flatMap(round => [round.markdown, round.draftMarkdown]), ...(session.questions ?? []).flatMap(question => [question.answer, question.draftAnswer])];
  return rosterFor(session, [...history, draftMarkdown].filter(Boolean).join("\n"));
}
export function parseSpeeches(markdown: string): Array<{ name: string; role: string; text: string }> {
  const body = markdown.split(/^# (?:觀察者整理|Observer(?:[’']s)? notes)\s*$/m, 1)[0];
  const people = parseGuests(body), roles = new Map(people.map(person => [person.name, person.role]));
  return [...body.matchAll(/^###\s+([^\n]+)\n([\s\S]*?)(?=^###\s|$(?![\s\S]))/gm)].map(match => {
    const [name, explicitRole] = match[1].split(/[｜|]/, 2).map(value => value.trim()); const person = people.find(entry => entry.name === name);
    return { name, role: explicitRole || person?.role || roles.get(name) || "", text: match[2].trim() };
  }).filter(item => item.text && item.role && !/^(觀察者整理|Observer(?:[’']s)? notes)$/.test(item.name));
}
function defaults(): GuestCounts { return { experts: 4, "cross-domain": 1, generalist: 1, affected: 1 }; }
function total(counts: GuestCounts): number { return Object.values(counts).reduce((sum, count) => sum + count, 0); }
export class CoffeeTablesView extends ItemView {
  private store!: CoffeeStorage; private engine: CoffeeEngine | null = null; private unsubscribe: (() => void) | null = null;
  private closed = false; private generation = 0; private navigationGeneration = 0; private homeGeneration = 0; private listGeneration = 0; private selectedPath = ""; private previewVisible = false; private homeQuery = ""; private tableFilter: TableListFilter = "all"; private focusedTopic: string | null = null; private recoveredPendingCreates = false; private scrollEpoch = 0; private homePane: "main"|"list" = "main"; private homeForm: Record<string,string> = {}; private homeEdit: CoffeeSession | null = null; private homeMainScrollTop = 0; private homeListScrollTop = 0; private firstRoomScroll: "top"|"bottom"|null = null; private markdownJobs: Promise<void>[]|null = null; private renderTimer: number | null = null; private statusTimer: number | null = null; private stateSignature = ""; private composerValues = new Map<string,string>(); private suppressStateRestore = false;
  constructor(leaf: WorkspaceLeaf, private plugin: VisualAgentMapPlugin) { super(leaf); }
  getViewType(): string { return COFFEE_TABLES_VIEW_TYPE; } getDisplayText(): string { return COFFEE_TABLES_NAME; } getIcon(): string { return "coffee"; }
  private tr(en: string, zh: string): string { return this.plugin.settings.language === "zh-TW" ? zh : en; }
  async refreshForLanguageChange(): Promise<void> {
    if (this.closed) return;
    if (this.engine) { this.render(); return; }
    const active = this.contentEl.ownerDocument.activeElement as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null;
    const field = active?.dataset.ctHomeField, start = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement ? active.selectionStart : null, end = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement ? active.selectionEnd : null;
    this.homeForm.advancedOpen = this.contentEl.querySelector<HTMLDetailsElement>(".ct-advanced-settings")?.open ? "true" : this.homeForm.advancedOpen ?? "false";
    this.homeForm.topicIdeasOpen = this.contentEl.querySelector<HTMLDetailsElement>(".ct-topic-ideas")?.open ? "true" : this.homeForm.topicIdeasOpen ?? "false";
    this.homeMainScrollTop = this.contentEl.querySelector<HTMLElement>(".ct-home-main")?.scrollTop ?? this.homeMainScrollTop;
    await this.home();
    if (field) { const replacement = this.contentEl.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[data-ct-home-field="${field}"]`); replacement?.focus(); if (replacement instanceof HTMLInputElement || replacement instanceof HTMLTextAreaElement) { try { replacement.setSelectionRange(start ?? replacement.value.length, end ?? replacement.value.length); } catch { /* Selection is unavailable for this input type. */ } } }
  }
  async onOpen(): Promise<void> { await this.plugin.ready; this.closed = false; this.suppressStateRestore = false; this.store = this.plugin.coffeeStorage ?? new CoffeeStorage(this.app.vault, this.plugin.settings.workspaceFolder); this.contentEl.addClass("ct-view"); await this.home(); }
  async onClose(): Promise<void> { this.closed = true; this.generation++; this.unsubscribe?.(); this.unsubscribe = null; if (this.renderTimer !== null) window.clearTimeout(this.renderTimer); if (this.statusTimer !== null) window.clearInterval(this.statusTimer); }
  getState(): Record<string, unknown> { return { sessionId: this.engine?.session.id ?? null }; }
  async setState(state: { sessionId?: string }, result: ViewStateResult): Promise<void> { await this.plugin.ready; if (!this.store) this.store = this.plugin.coffeeStorage ?? new CoffeeStorage(this.app.vault, this.plugin.settings.workspaceFolder); if (state.sessionId && !this.suppressStateRestore && state.sessionId !== this.engine?.session.id) await this.loadSession(state.sessionId); await super.setState(state, result); }
  private returnHome(edit?: CoffeeSession): void { this.suppressStateRestore = true; if (!edit) this.homeEdit = null; void this.home(edit); this.app.workspace.requestSaveLayout(); }
  private button(parent: HTMLElement, label: string, action: () => void | Promise<void>, disabled = false): HTMLButtonElement { const button = parent.createEl("button", { text: label }); button.disabled = disabled; button.addEventListener("click", () => { void Promise.resolve().then(action).catch((error: unknown) => new Notice(error instanceof Error ? error.message : String(error))); }); return button; }
  private async home(edit?: CoffeeSession): Promise<void> {
    const requestedEdit = !!edit;
    if (!edit && this.homeEdit) edit = this.homeEdit;
    if (requestedEdit && edit) { this.homeEdit = edit; const priorGuests = edit.guests?.guests?.length ? edit.guests.guests : edit.guests?.background ? [{ id: crypto.randomUUID(), category: "experts" as const, description: edit.guests.background }] : []; this.homeForm = { ...this.homeForm, topic: edit.topic, topicIdeaId: "", topicEdited: "true", model: edit.model, reasoning: edit.reasoning, hostCount: String(edit.guests?.hostCount ?? 2), custom: edit.guests?.customPrompt ?? "", invites: JSON.stringify(priorGuests), ...Object.fromEntries(CATEGORIES.map(item => [`count-${item.id}`, String(edit.guests?.counts[item.id] ?? defaults()[item.id])])) }; }
    const generation = ++this.generation; this.navigationGeneration++; this.unsubscribe?.(); this.unsubscribe = null; if (this.closed || generation !== this.generation) return;
    if (!this.recoveredPendingCreates) { try { await this.store.recoverPendingCreates(); await this.store.recoverMoves(); } catch (error) { new Notice(error instanceof Error ? error.message : String(error)); } this.recoveredPendingCreates = true; } if (this.closed || generation !== this.generation) return;
    this.engine = null; this.contentEl.empty(); const shell = this.contentEl.createDiv("ct-home-shell"); const home = shell.createDiv("ct-home-main"); home.scrollTop = this.homeMainScrollTop; home.addEventListener("scroll", () => this.homeMainScrollTop = home.scrollTop); const tabs = shell.createDiv("ct-home-tabs"); this.button(tabs, this.tr("Setup and preview", "主區"), () => { this.homePane = "main"; shell.dataset.pane = "main"; }); this.button(tabs, this.tr("Table list", "桌聊清單"), () => { this.homePane = "list"; shell.dataset.pane = "list"; }); shell.dataset.pane = this.homePane;
    const title = home.createDiv("ct-home-title"); const cup = title.createSpan({ cls: "ct-coffee-icon" }); setIcon(cup, "coffee"); title.createEl("h2", { text: COFFEE_TABLES_NAME });
    home.createEl("p", { cls: "ct-intro", text: this.tr("Bring different AI perspectives together to spot blind spots, unexpected connections and better questions.", "讓不同背景的 AI 來賓一起聊，幫你發現盲點、意外連結，以及更值得問的問題。") });
    home.createEl("p", { cls: "ct-muted", text: this.tr("Guests and experiences are AI simulations.", "來賓與經驗為 AI 模擬。") });
    const setup = home.createDiv("ct-home-section"); setup.createEl("h3", { text: this.tr("Start a table", "開一桌") });
    const topic = setup.createEl("textarea", { attr: { "aria-label": this.tr("Topic", "主題"), placeholder: this.tr("What would you like to explore?", "今天想探索什麼問題？"), maxlength: "1200", rows: "3", "data-ct-home-field": "topic" } });
    const topicWasEdited = this.homeForm.topicEdited === "true", ideaId = this.homeForm.topicIdeaId ?? "";
    const suggestedTopic = ideaId && !topicWasEdited ? coffeeTopicText(ideaId, this.plugin.settings.language) : undefined;
    topic.value = topicWasEdited ? this.homeForm.topic ?? "" : suggestedTopic ?? this.homeForm.topic ?? pickCoffeeTopic(this.plugin.settings.language, this.homeForm.previousTopic ?? "");
    if (!edit && !topicWasEdited && !ideaId) this.homeForm.topicIdeaId = COFFEE_TOPICS.find(item => item[this.plugin.settings.language === "en" ? "en" : "zh"] === topic.value)?.id ?? "";
    const ideas = setup.createEl("details", { cls: "ct-topic-ideas" }); ideas.open = this.homeForm.topicIdeasOpen === "true"; ideas.addEventListener("toggle", () => { this.homeForm.topicIdeasOpen = String(ideas.open); }); ideas.createEl("summary", { text: this.tr("Browse 20 topic ideas", "看看 20 個討論主題") }); const ideaList = ideas.createDiv("ct-topic-list"); for (const item of COFFEE_TOPICS) { const value = item[this.plugin.settings.language === "en" ? "en" : "zh"]; this.button(ideaList, value, () => { topic.value = value; this.homeForm.topicIdeaId = item.id; this.homeForm.topicEdited = "false"; snapshotForm(); }); }
    this.button(setup, this.tr("Surprise me with a topic", "換個題目"), () => { const previous = topic.value; topic.value = pickCoffeeTopic(this.plugin.settings.language, previous); this.homeForm.topicIdeaId = COFFEE_TOPICS.find(item => item[this.plugin.settings.language === "en" ? "en" : "zh"] === topic.value)?.id ?? ""; this.homeForm.topicEdited = "false"; this.homeForm.previousTopic = previous; snapshotForm(); });
    const advanced = setup.createEl("details", { cls: "ct-advanced-settings" }); advanced.open = this.homeForm.advancedOpen === "true"; advanced.addEventListener("toggle", () => { this.homeForm.advancedOpen = String(advanced.open); }); const advancedSummary = advanced.createEl("summary", { text: this.tr("Adjust this table", "調整這桌") }); const models = advanced.createDiv("ct-model-row"); const model = models.createEl("select", { attr: { "aria-label": this.tr("AI model", "AI 模型") } }); const reasoning = models.createEl("select", { attr: { "aria-label": this.tr("Reasoning effort", "推理強度") } });
    const efforts: Record<string, [string, string]> = { auto: ["Auto", "自動"], low: ["Low", "低"], medium: ["Medium", "中"], high: ["High", "高"] };
    const setReasoning = (): void => { const selected = reasoning.value || this.homeForm.reasoning || edit?.reasoning || this.plugin.settings.cliReasoning; const values = ["auto", ...this.plugin.coffeeReasoningEfforts(model.value).filter(value => Object.hasOwn(efforts, value))]; reasoning.empty(); values.forEach(value => reasoning.createEl("option", { value, text: this.tr(...efforts[value]) })); reasoning.value = values.includes(selected) ? selected : "auto"; };
    const setModels = (available: string[]): void => { model.empty(); available.forEach(id => model.createEl("option", { value: id, text: this.plugin.modelLabel(id) })); const selected = this.homeForm.model || edit?.model || ""; model.value = available.includes(selected) ? selected : available.includes(this.plugin.settings.cliModel) ? this.plugin.settings.cliModel : available[0] ?? ""; setReasoning(); };
    model.dataset.ctHomeField = "model"; reasoning.dataset.ctHomeField = "reasoning";
    const modelStatus = advanced.createEl("p", { cls: "ct-muted", text: this.tr("Loading available models…", "正在載入可用模型…") }); setModels(this.plugin.availableModels()); model.disabled = true; reasoning.disabled = true;
    const old = edit?.guests, counts: GuestCounts = old?.counts ? { ...old.counts } : defaults();
    const hostRow = advanced.createDiv("ct-host-count"); hostRow.createEl("label", { text: this.tr("Hosts", "主持人") }); const hostCount = hostRow.createEl("select", { attr: { "aria-label": this.tr("Number of hosts", "主持人人數"), "data-ct-home-field": "hostCount" } }); for (let count = 1; count <= 4; count++) hostCount.createEl("option", { value: String(count), text: String(count) }); hostCount.value = String(this.homeForm.hostCount ?? old?.hostCount ?? 2); hostRow.createEl("p", { cls: "ct-muted", text: this.tr("One host can combine both facilitation styles.", "一位主持人可以同時負責抓矛盾與好奇追問。") }); const hostRisk = hostRow.createEl("p", { cls: "ct-risk-warning is-hidden", attr: { role: "status" }, text: this.tr("More than two hosts may leave less room for guests to speak.", "主持人超過兩位，可能會占用來賓接話的空間。") });
    const guestSection = advanced.createDiv("ct-guests"); guestSection.createEl("h4", { text: this.tr("Choose your guests", "選擇來賓") });
    const guestIntro = this.tr("Each perspective adds a different kind of question and challenge.", "不同視角會帶來不同問題與挑戰。"); guestSection.createEl("p", { cls: "ct-muted", text: guestIntro });
    const countInputs = new Map<GuestCategory, HTMLInputElement>();
    const updateAdvancedSummary = (): void => { const selectedModel = model.value ? this.plugin.modelLabel(model.value) : this.tr("Select a model", "選擇模型"); const guests = [...countInputs.values()].reduce((sum, input) => sum + (Number(input.value) || 0), 0); advancedSummary.setText(`${this.tr("Adjust this table", "調整這桌")} · ${selectedModel} · ${hostCount.value} ${this.tr("hosts", "位主持人")} + ${guests} ${this.tr("guests", "位來賓")}`); };
    for (const category of CATEGORIES) { const row = guestSection.createDiv("ct-count-row"); const label = row.createEl("label"); label.createSpan({ text: this.tr(category.en, category.zh) }); const input = label.createEl("input", { attr: { type: "number", min: "0", max: "8", step: "1", "aria-label": this.tr(category.en, category.zh), "data-ct-home-field": `count-${category.id}` } }); input.value = this.homeForm[`count-${category.id}`] ?? String(counts[category.id]); countInputs.set(category.id, input); row.createEl("p", { cls: "ct-muted", text: this.tr(category.descEn, category.descZh) }); }
    const warning = guestSection.createEl("p", { cls: "ct-risk-warning is-hidden", attr: { role: "status" } });
    const invites = advanced.createDiv("ct-invites"); invites.createEl("h4", { text: this.tr("Guests you have in mind", "想邀請的來賓") }); const inviteRows: Array<{ id: string; category: HTMLSelectElement; description: HTMLInputElement; row: HTMLElement }> = [];
    const savedInvites = (() => { try { return JSON.parse(this.homeForm.invites ?? "[]") as NamedGuest[]; } catch { return []; } })();
    const addInvite = (guest?: NamedGuest): void => { const row = invites.createDiv("ct-invite-row"), id = guest?.id ?? crypto.randomUUID(); const select = row.createEl("select", { attr: { "aria-label": this.tr("Guest category", "來賓類別"), "data-ct-home-field": `invite-category-${id}` } }); CATEGORIES.forEach(item => select.createEl("option", { value: item.id, text: this.tr(item.en, item.zh) })); const description = row.createEl("input", { attr: { type: "text", maxlength: "160", placeholder: this.tr("Name or background, e.g. a frontline support worker", "姓名或背景，例如：第一線客服，輪班十年"), "aria-label": this.tr("Guest name or background", "來賓姓名或背景"), "data-ct-home-field": `invite-description-${id}` } }); if (guest) { select.value = guest.category; description.value = guest.description; } const remove = this.button(row, this.tr("Remove", "移除"), () => { row.remove(); const rowIndex = inviteRows.findIndex(item => item.row === row); if (rowIndex >= 0) inviteRows.splice(rowIndex, 1); updateWarning(); snapshotForm(); }); inviteRows.push({ id, category: select, description, row }); select.addEventListener("change", () => { updateWarning(); snapshotForm(); }); description.addEventListener("input", () => { updateWarning(); snapshotForm(); }); void remove; };
    if (this.homeForm.invites !== undefined) savedInvites.forEach(guest => addInvite(guest)); else if (old?.guests?.length) old.guests.forEach(guest => addInvite(guest)); else savedInvites.forEach(guest => addInvite(guest));
    this.button(invites, this.tr("Add a guest", "新增來賓"), () => { addInvite(); snapshotForm(); });
    const customLabel = advanced.createEl("label", { cls: "ct-custom-prompt-label" }); customLabel.createSpan({ text: this.tr("Extra requests for this table", "這桌的額外要求（選填）") }); const custom = customLabel.createEl("textarea", { attr: { rows: "3", maxlength: "4000", placeholder: this.tr("e.g. Focus on what a small company can do; avoid management jargon.", "例如：多談小公司能採取的做法，少用管理術語。"), "data-ct-home-field": "custom" } }); custom.value = this.homeForm.custom ?? old?.customPrompt ?? "";
    const snapshotForm = (): void => { this.homeForm = { ...this.homeForm, topic: topic.value, model: model.value, reasoning: reasoning.value, custom: custom.value, hostCount: hostCount.value, ...Object.fromEntries([...countInputs].map(([key, input]) => [`count-${key}`, input.value])), invites: JSON.stringify(inviteRows.map(item => ({ id: item.id, category: item.category.value, description: item.description.value }))) }; };
    const updateWarning = (): void => { const current = Object.fromEntries([...countInputs].map(([key, input]) => [key, Number(input.value)])) as GuestCounts; const assigned = Object.fromEntries(CATEGORIES.map(item => [item.id, inviteRows.filter(guest => guest.category.value === item.id && guest.description.value.trim()).length])) as GuestCounts; const overflow = CATEGORIES.filter(item => assigned[item.id] > current[item.id]); const n = total(current); warning.toggleClass("is-hidden", !(n > 7 || n < 1 || n > 12 || overflow.length)); warning.setText(overflow.length ? this.tr(`There are more named guests than ${overflow.map(item => item.en).join(", ")} places. Increase the count or remove a guest.`, `${overflow.map(item => item.zh).join("、")}人數超過設定名額，請增加名額或移除來賓。`) : n < 1 || n > 12 ? this.tr("Choose 1–12 guests in total.", "來賓總數需介於 1–12 人。") : n > 7 ? this.tr("More guests can mean more waiting and less room for each person to go deeper.", "來賓越多，等待可能越久，每個人深入接話的空間也可能變少。") : ""); };
    countInputs.forEach(input => input.addEventListener("input", () => { updateWarning(); updateAdvancedSummary(); snapshotForm(); })); updateWarning(); updateAdvancedSummary();
    topic.addEventListener("input", () => { this.homeForm.topicEdited = "true"; snapshotForm(); }); custom.addEventListener("input", snapshotForm); model.addEventListener("change", () => { setReasoning(); updateAdvancedSummary(); snapshotForm(); }); reasoning.addEventListener("change", snapshotForm); hostCount.addEventListener("change", () => { hostRisk.toggleClass("is-hidden", Number(hostCount.value) <= 2); updateAdvancedSummary(); snapshotForm(); }); hostRisk.toggleClass("is-hidden", Number(hostCount.value) <= 2); snapshotForm();
    const start = this.button(setup, this.tr(edit ? "Open a new table with these settings" : "Open table", edit ? "用這些設定開新桌" : "開一桌"), async () => {
      const finalCounts = Object.fromEntries([...countInputs].map(([key, input]) => [key, Number(input.value)])) as GuestCounts; const finalTotal = total(finalCounts); const guests: NamedGuest[] = inviteRows.filter(item => item.description.value.trim()).map(item => ({ id: crypto.randomUUID(), category: item.category.value as GuestCategory, description: item.description.value.trim() }));
      const over = CATEGORIES.some(item => guests.filter(guest => guest.category === item.id).length > finalCounts[item.id]);
      if (!topic.value.trim() || !model.value || finalTotal < 1 || finalTotal > 12 || Object.values(finalCounts).some(value => !Number.isInteger(value) || value < 0 || value > 8) || over) { warning.removeClass("is-hidden"); topic.focus(); return; }
      start.disabled = true; try { await this.plugin.confirmAiUsage(model.value, async () => { if (this.closed || generation !== this.generation) return; const settings: GuestSettings = { counts: finalCounts, guests, background: "", customPrompt: custom.value, hostCount: Number(hostCount.value) }; const session = createSession(topic.value, model.value, reasoning.value, this.plugin.settings.language, settings); await this.store.save(session); if (this.closed || generation !== this.generation) return; this.homeForm = {}; this.homeEdit = null; this.attach(session); void this.engine?.start(); }); } finally { if (!this.closed && generation === this.generation) start.disabled = false; }
    }); start.addClass("mod-cta"); start.disabled = true;
    const modelLoad = this.plugin.refreshCoffeeModels(); void modelLoad.then(available => { if (this.closed || generation !== this.generation) return; setModels(available); updateAdvancedSummary(); modelStatus.remove(); model.disabled = false; reasoning.disabled = false; start.disabled = available.length === 0; }).catch(() => { if (!this.closed && generation === this.generation) modelStatus.setText(this.tr("Could not load models. Check provider setup and try again.", "無法載入模型，請檢查 provider 設定後重試。")); });
    const samples = home.createDiv("ct-home-section"); samples.createEl("h3", { text: this.tr("See a sample conversation", "看看示範桌聊") }); for (const sample of [COFFEE_SAMPLE_ZH, COFFEE_SAMPLE_EN]) this.button(samples, sample.language === "en" ? this.tr("English sample · Should Our Company Adopt AI?", "英文範例 · 公司應該導入 AI 嗎？") : this.tr("Traditional Chinese sample · Should Our Company Adopt AI?", "繁體中文範例 · 公司到底要不要推 AI？"), async () => this.openSample(sample.language)).addClass("ct-session-link");
    const preview = home.createDiv("ct-preview is-hidden"); const aside = shell.createDiv("ct-home-sidebar"); const searchRow = aside.createDiv("ct-list-search"); const searchIcon = searchRow.createSpan({ cls: "ct-search-icon", attr: { "aria-hidden": "true" } }); setIcon(searchIcon, "search"); const search = searchRow.createEl("input", { attr: { type: "search", placeholder: this.tr("Search topics", "搜尋主題"), "aria-label": this.tr("Search topics", "搜尋主題"), "data-ct-home-field": "search" } }); search.value = this.homeQuery; const clear = this.button(searchRow, this.tr("Clear", "清除"), () => { search.value = ""; this.homeQuery = ""; void renderList(); }); clear.addClass("ct-search-clear"); search.addEventListener("input", () => { this.homeQuery = search.value; void renderList(); });
    const filterBar = aside.createDiv("ct-list-filters"), filterButtons = new Map<TableListFilter, HTMLButtonElement>(); const filterLabels: Record<TableListFilter,[string,string]> = { all: ["All", "全部"], generating: ["Generating", "生成中"], unfinished: ["Unfinished", "未完成"], completed: ["Completed", "已完成"] };
    for (const filter of ["all", "generating", "unfinished", "completed"] as const) { const button = this.button(filterBar, this.tr(...filterLabels[filter]), () => { this.tableFilter = filter; this.focusedTopic = null; updateFilters(); void renderList(); }); button.setAttribute("aria-pressed", String(this.tableFilter === filter)); filterButtons.set(filter, button); }
    const topicFocusRow = aside.createDiv("ct-topic-focus is-hidden"); const topicFocusText = topicFocusRow.createSpan(); this.button(topicFocusRow, this.tr("Show all tables", "顯示全部桌聊"), () => { this.focusedTopic = null; updateFilters(); void renderList(); });
    const updateFilters = (): void => { for (const [filter, button] of filterButtons) { button.toggleClass("is-active", this.tableFilter === filter && !this.focusedTopic); button.setAttribute("aria-pressed", String(this.tableFilter === filter && !this.focusedTopic)); } topicFocusRow.toggleClass("is-hidden", !this.focusedTopic); if (this.focusedTopic) topicFocusText.setText(this.tr(`Same topic: ${this.focusedTopic}`, `同一主題：${this.focusedTopic}`)); };
    const listTools = aside.createDiv("ct-list-tools"); this.button(listTools, this.tr("Organize existing tables", "整理既有桌聊"), async () => { const result = await this.store.organizeExisting(); new Notice(this.tr(`Moved ${result.moved}; skipped ${result.skipped}.`, `已整理 ${result.moved} 場；略過 ${result.skipped} 場。`)); void renderList(); }); this.button(listTools, this.tr("Recently deleted", "最近刪除"), async () => { const panel = aside.createDiv("ct-trash-list"); panel.empty(); panel.createEl("h3", { text: this.tr("Recently deleted", "最近刪除") }); const deleted = await this.store.deletedTables(); for (const item of deleted) { const row = panel.createDiv("ct-trash-row"); row.createSpan({ text: item.topic }); this.button(row, this.tr("Restore", "復原"), async () => { await this.store.restoreDeleted(item.path); this.plugin.coffeeManager?.restore(item.id); panel.remove(); void renderList(); }); } if (!deleted.length) panel.createEl("p", { cls: "ct-muted", text: this.tr("No deleted tables.", "沒有已刪除的桌聊。") }); });
    const listScroller = aside.createDiv("ct-list-scroll"); const list = listScroller.createDiv("ct-list-content"); listScroller.scrollTop = this.homeListScrollTop; listScroller.addEventListener("scroll", () => this.homeListScrollTop = listScroller.scrollTop);
    const deleteTable = async (session: CoffeeSession, path?: string): Promise<void> => {
      if (!await new CoffeeDeleteModal(this.app, session.topic, this.plugin.settings.language === "zh-TW").confirm()) return;
      const manager = this.plugin.coffeeManager; let engine: CoffeeEngine | undefined;
      try { engine = await manager?.prepareDelete(session.id); await this.store.delete(session.id, path); manager?.completeDelete(session.id, engine); if (this.closed) return; this.selectedPath = ""; this.suppressStateRestore = true; await this.home(); this.app.workspace.requestSaveLayout(); }
      catch (error) { manager?.cancelDelete(session.id, engine); throw error; }
    };
    const openMarkdown = async (id: string): Promise<void> => { const file = await this.store.openMarkdown(id); await this.app.workspace.getLeaf(false).openFile(file); };
    const showPreview = async (path: string): Promise<void> => { const token = ++this.navigationGeneration; this.homeGeneration++; this.homePane = "main"; shell.dataset.pane = "main"; this.selectedPath = path; this.previewVisible = true; preview.empty(); preview.removeClass("is-hidden"); setup.addClass("is-hidden"); samples.addClass("is-hidden"); preview.createEl("p", { cls: "ct-muted", text: this.tr("Loading saved notes…", "正在讀取已保存的整理…") }); try { const inspected = await this.store.inspectReadOnly(path); let session: CoffeeSession = inspected.version === 1 ? { ...copyLegacySession(inspected), createdAt: inspected.createdAt, updatedAt: inspected.updatedAt } : inspected; const active = this.plugin.coffeeManager?.get(session.id); if (active) session = active.session; if (this.closed || token !== this.navigationGeneration) return; preview.empty(); preview.createEl("h2", { text: session.topic }); preview.createEl("p", { cls: "ct-muted", text: `${this.tr("Latest update", "最後更新")} · ${new Date(session.lastCompletedAt || session.updatedAt || session.createdAt).toLocaleString()}` }); if (session.dirtyNotes) preview.createEl("p", { cls: "ct-warning", text: this.tr("These notes predate later conversation changes.", "這份整理產生後，對談內容有過更新。") }); const notes = session.observerNotes?.[0] ?? session.rounds?.find(round => round.notes)?.notes ?? ""; if (notes) void MarkdownRenderer.render(this.app, notes, preview.createDiv("ct-preview-notes markdown-rendered"), path, this); else preview.createEl("p", { cls: "ct-muted", text: this.tr("No observer notes yet. You can still enter this table.", "尚無觀察者整理，仍可進入桌聊。") }); this.button(preview, this.tr("Enter this table", "進入這個桌聊"), () => { this.suppressStateRestore = true; void this.loadSession(path, true); }).addClass("mod-cta"); this.button(preview, this.tr("Open Markdown", "開啟 Markdown"), () => openMarkdown(path)); this.button(preview, this.tr("Delete table", "刪除桌聊"), () => deleteTable(session, path)); this.button(preview, this.tr("Open new table", "開新桌"), () => { this.navigationGeneration++; this.homeGeneration++; this.suppressStateRestore = true; this.selectedPath = ""; this.previewVisible = false; preview.addClass("is-hidden"); setup.removeClass("is-hidden"); samples.removeClass("is-hidden"); this.app.workspace.requestSaveLayout(); }); } catch (error) { if (this.closed || token !== this.navigationGeneration) return; preview.empty(); preview.createEl("p", { cls: "ct-error", text: this.tr(`Preview unavailable: ${error instanceof Error ? error.message : String(error)}`, `無法預覽：${error instanceof Error ? error.message : String(error)}`) }); this.button(preview, this.tr("Enter this table", "進入這個桌聊"), () => { this.suppressStateRestore = true; void this.loadSession(path, true); }).addClass("mod-cta"); } };
    const renderList = async (): Promise<void> => {
      const token = ++this.listGeneration, oldTop = listScroller.scrollTop, entries: TableListItem[] = [];
      for (const file of this.store.list().filter(item => item.extension === "md")) {
        try {
          const inspected = await this.store.inspectReadOnly(file.path); let session: CoffeeSession = inspected.version === 1 ? { ...copyLegacySession(inspected), createdAt: inspected.createdAt, updatedAt: inspected.updatedAt } : inspected;
          const active = this.plugin.coffeeManager?.get(session.id); if (active) session = active.session;
          entries.push({ id: session.id, path: file.path, topic: session.topic, status: effectiveTableStatus(session, active?.busy), createdAt: session.createdAt, updatedAt: session.updatedAt, lastGenerationStartedAt: session.lastGenerationStartedAt, lastCompletedAt: session.lastCompletedAt, model: session.model });
        } catch { entries.push({ id: `unreadable:${file.path}`, path: file.path, topic: file.basename, status: "error", createdAt: new Date(file.stat.ctime).toISOString(), updatedAt: new Date(file.stat.mtime).toISOString(), model: "", unreadable: true }); }
        if (this.closed || token !== this.listGeneration) return;
      }
      if (this.closed || token !== this.listGeneration) return;
      list.empty(); updateFilters(); const visible = selectTables(entries, this.homeQuery, this.tableFilter, this.focusedTopic); list.createEl("h3", { cls: "ct-list-heading", text: `${this.tr("Tables", "桌聊")} (${visible.length})` });
      for (const item of visible) {
        const time = tableTime(item), timestamp = new Date(time.value), status = item.status === "generating" ? this.tr("Generating", "生成中") : item.status === "completed" ? this.tr("Complete", "已完成") : item.status === "error" ? this.tr("Interrupted", "中斷") : this.tr("Draft", "草稿");
        const entry = list.createDiv("ct-list-entry"), button = this.button(entry, "", () => { if (item.status === "generating") void this.loadSession(item.path); else void showPreview(item.path); });
        button.empty(); button.addClass("ct-list-item"); button.createSpan({ cls: "ct-list-title", text: item.topic }); const meta = button.createDiv("ct-list-meta"); meta.createSpan({ text: formatTableTime(time.value, Date.now(), this.plugin.settings.language) }); const badge = meta.createSpan({ cls: `ct-status-badge ct-status-${item.status}`, text: status }); badge.setAttribute("aria-label", status); if (time.isFallback) meta.createSpan({ cls: "ct-list-fallback", text: this.tr("Last updated", "最後更新") });
        if (item.unreadable) { button.addClass("ct-list-unreadable"); button.disabled = true; } if (this.selectedPath === item.path) button.addClass("is-selected"); button.setAttribute("aria-current", this.selectedPath === item.path ? "true" : "false"); if (Number.isFinite(timestamp.getTime())) button.setAttribute("title", `${item.topic}\n${timestamp.toLocaleString()}${item.model ? ` · ${item.model}` : ""}`);
        const sameCount = topicTableCount(item.topic, entries); if (!item.unreadable && sameCount > 1) { const same = entry.createEl("button", { cls: "ct-same-topic-link", text: this.tr(`Same topic · ${sameCount} tables`, `同題共 ${sameCount} 場`) }); same.addEventListener("click", event => { event.preventDefault(); event.stopPropagation(); this.focusedTopic = item.topic.trim(); this.tableFilter = "all"; this.homeQuery = ""; search.value = ""; updateFilters(); void renderList(); }); }
        if (!item.unreadable) {
          const actions = entry.createEl("button", { cls: "ct-row-menu-trigger", text: "⋯", attr: { "aria-label": this.tr("Table actions", "桌聊操作"), title: this.tr("Table actions", "桌聊操作") } });
          actions.addEventListener("click", event => {
            event.preventDefault(); event.stopPropagation(); const menu = new Menu();
            menu.addItem(option => option.setTitle(this.tr("Enter this table", "進入這個桌聊")).onClick(() => { if (item.status === "generating") void this.loadSession(item.path); else void this.loadSession(item.path, true); }));
            menu.addItem(option => option.setTitle(this.tr("Open Markdown", "開啟 Markdown")).onClick(() => void openMarkdown(item.path)));
            menu.addItem(option => option.setTitle(this.tr("Edit settings and start another", "編輯設定，再開一桌")).onClick(async () => { const session = await this.store.inspectReadOnly(item.path); if (session.version === 3) await this.home(session); }));
            menu.addItem(option => option.setTitle(this.tr("Delete table", "刪除桌聊")).setWarning(true).onClick(async () => { const stored = await this.store.inspectReadOnly(item.path), session = stored.version === 3 ? stored : copyLegacySession(stored); await deleteTable(session, item.path); }));
            menu.showAtMouseEvent(event);
          });
        }
      }
      if (!visible.length) list.createEl("p", { cls: "ct-muted", text: this.homeQuery || this.focusedTopic ? this.tr("No matching tables.", "找不到符合的桌聊。") : this.tr("Your tables will appear here.", "桌聊會顯示在這裡。") }); listScroller.scrollTop = oldTop;
    };
    void renderList(); if (this.statusTimer !== null && typeof window.clearInterval === "function") window.clearInterval(this.statusTimer); this.statusTimer = typeof window.setInterval === "function" ? window.setInterval(() => { const focused = this.contentEl.ownerDocument.activeElement; if (!this.closed && this.contentEl.querySelector(".ct-home-sidebar") && !focused?.closest(".ct-list-entry, .ct-list-filters, .ct-list-search")) void renderList(); }, 3000) : null; if (this.previewVisible && this.selectedPath) void showPreview(this.selectedPath);
  }
  private async openSample(language: "zh-TW" | "en"): Promise<void> { const sample = language === "en" ? COFFEE_SAMPLE_EN : COFFEE_SAMPLE_ZH, now = new Date().toISOString(); const roles = new Map(parseGuests(sample.markdown).map(person => [person.name, person.role])); const markdown = sample.markdown.replace(/^###\s+([^\n|｜]+)$/gm, (heading, name: string) => `### ${name}｜${roles.get(name.trim()) ?? "Guest"}`); const session = createSession(sample.topic, "Built-in sample", "—", language); session.id = `sample-${language === "en" ? "en" : "zh"}`; session.createdAt = now; session.updatedAt = now; session.status = "completed"; session.transcriptMarkdown = markdown; session.rounds = [{ id: "sample-round", markdown, notes: observerNotes(markdown), status: "completed", createdAt: now }]; session.observerNotes = [observerNotes(markdown)]; session.questions = [{ id: `sample-question-${language === "en" ? "en" : "zh"}`, question: sample.question, answer: sample.answer, status: "complete", createdAt: now }]; this.attach(session); }
  private async loadSession(path: string, startAtTop = false): Promise<void> { const generation = ++this.navigationGeneration; this.generation++; this.unsubscribe?.(); let stored: AnyCoffeeSession; try { stored = await this.store.load(path); } catch (error) { const message = error instanceof Error ? error.message : String(error); if (/changed outside|外部修改|outside this room/i.test(message)) { const latest = await this.store.inspect(path).catch(() => null); if (this.closed || generation !== this.navigationGeneration) return; if (latest && latest.version === 3) { const cached = this.plugin.coffeeManager?.get(latest.id); if (cached) { if (cached.busy) await cached.stop(); if (this.closed || generation !== this.navigationGeneration) return; this.attach(cached.session); cached.reportPersistenceError(new Error(message)); return; } } } throw error; } if (this.closed || generation !== this.navigationGeneration) return; if (stored.version === 1) { this.attachLegacy(stored); return; } this.attach(stored, startAtTop); }
  private attachLegacy(legacy: Extract<AnyCoffeeSession, { version: 1 }>): void { this.navigationGeneration++; this.contentEl.empty(); const room = this.contentEl.createDiv("ct-room"); room.createEl("h2", { text: legacy.topic }); this.button(room, this.tr("All tables", "所有桌聊"), () => this.returnHome()); room.createEl("p", { cls: "ct-muted", text: this.tr("Older saved table · read only", "舊版桌聊紀錄 · 唯讀") }); void MarkdownRenderer.render(this.app, copyLegacySession(legacy).transcriptMarkdown, room.createDiv("ct-scroll markdown-rendered"), this.store.sessionPath(legacy.id), this); }
  private attach(session: CoffeeSession, startAtTop = true): void { this.navigationGeneration++; this.unsubscribe?.(); if (this.statusTimer !== null && typeof window.clearInterval === "function") { window.clearInterval(this.statusTimer); this.statusTimer = null; } this.previewVisible = false; this.firstRoomScroll = startAtTop && session.status === "completed" ? "top" : "bottom"; this.composerValues.clear(); this.engine = this.plugin.coffeeManager?.open(session) ?? new CoffeeEngine(session, request => this.plugin.runCoffeeRequest(request), value => this.store.save(value)); this.unsubscribe = this.engine.subscribe(() => this.refresh()); this.render(); this.app.workspace.requestSaveLayout(); }
  private render(): void {
    const engine = this.engine; if (!engine || this.closed) return; const priorScroll = this.contentEl.querySelector<HTMLElement>(".ct-chat-scroll"), hadPriorScroll = !!priorScroll, oldTop = priorScroll?.scrollTop ?? 0, wasBottom = !!priorScroll && priorScroll.scrollHeight - priorScroll.scrollTop - priorScroll.clientHeight < 100, firstScroll = hadPriorScroll ? null : this.firstRoomScroll, scrollEpoch = this.scrollEpoch, active = this.contentEl.ownerDocument.activeElement as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null, activeField = active?.dataset.ctField, activeValue = active?.value, activeStart = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement ? active.selectionStart : undefined, activeEnd = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement ? active.selectionEnd : undefined; this.firstRoomScroll = null; this.markdownJobs = []; this.contentEl.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("[data-ct-field]").forEach(field => this.composerValues.set(field.dataset.ctField!,field.value));
    this.contentEl.empty(); const room = this.contentEl.createDiv("ct-room"), fixed = room.createDiv("ct-fixed"), header = fixed.createDiv("ct-header"); header.createEl("h2", { text: engine.session.topic }); this.button(header, this.tr("All tables", "所有桌聊"), () => this.returnHome()); header.createEl("p", { cls: "ct-muted", text: `${this.plugin.modelLabel(engine.session.model)} · ${this.tr("AI simulated perspectives", "AI 虛構模擬視角")} · ${engine.session.language === "en" ? this.tr("Conversation: English", "對談語言：英文") : this.tr("Conversation: Traditional Chinese", "對談語言：繁體中文")}` });
    const roster = fixed.createDiv("ct-roster"), status = fixed.createDiv({ cls: "ct-status", attr: { role: "status", "aria-live": "polite" } }); if (engine.busy) this.button(fixed, this.tr("Stop", "停止生成"), () => engine.cancel()); if (!engine.session.id.startsWith("sample-")) this.button(fixed, this.tr("Open Markdown", "開啟 Markdown"), async () => { const file = await this.store.openMarkdown(engine.session.id); await this.app.workspace.getLeaf(false).openFile(file); });
    const body = room.createDiv("ct-room-columns"), tabs = body.createDiv("ct-pane-tabs"); body.dataset.pane = "chat"; const chatTab = this.button(tabs, this.tr("Conversation", "對談"), () => { body.dataset.pane = "chat"; }); const insightTab = this.button(tabs, this.tr("Insights", "洞見"), () => { body.dataset.pane = "insight"; }); chatTab.addClass("ct-pane-tab"); insightTab.addClass("ct-pane-tab"); const chatPanel = body.createDiv("ct-chat-panel"), scrolling = chatPanel.createDiv("ct-chat-scroll"), messages = scrolling.createDiv("ct-messages");
    const events: Array<{ at: string; type: "round" | "question" | "intervention"; index: number }> = [];
    (engine.session.rounds ?? []).forEach((round, index) => { if (round.markdown) events.push({ at: round.createdAt, type: "round", index }); }); engine.session.questions.forEach((question, index) => events.push({ at: question.createdAt ?? engine.session.createdAt, type: "question", index })); (engine.session.interventions ?? []).forEach((item, index) => { if (!item.roundId) events.push({ at: item.createdAt, type: "intervention", index }); }); events.sort((a,b) => a.at.localeCompare(b.at));
    for (const event of events) { if (event.type === "round") { const round = (engine.session.rounds ?? [])[event.index]; this.renderRound(round.markdown, round.id, messages); } else if (event.type === "question") { const question = engine.session.questions[event.index]; this.renderUserBubble(question.question, messages); if (question.answer) this.renderBubbles(question.answer, messages); if (question.status !== "complete") { const live = messages.createDiv({ cls: "ct-live-answer", attr: { "data-live-question-id": question.id } }); if (question.draftAnswer) this.renderStreaming(question.draftAnswer, live); } if (question.status === "error") messages.createEl("p", { cls: "ct-error", text: question.error }); if (question.status !== "complete") this.button(messages, this.tr("Retry", "重試"), () => { void engine.ask(question.question, question.id); }); } else { const item = engine.session.interventions![event.index]; this.renderUserBubble(item.text, messages); if (item.status === "failed") messages.createEl("small", { cls: "ct-muted", text: this.tr("Not delivered", "尚未送達") }); } }
    const draft = engine.session.status === "completed" ? "" : engine.session.draftMarkdown ?? ""; if (engine.busy && !draft) messages.createEl("p", { cls: "ct-waiting", text: this.tr("Waiting for the first words…", "等待第一段對談內容…") }); if (draft || engine.busy) { const round = [...(engine.session.rounds ?? [])].reverse().find(item => item.status === "generating"); const live = messages.createDiv("ct-live-draft"); if (draft) this.renderRound(draft, round?.id, live); }
    const latest = chatPanel.createDiv("ct-latest is-hidden"); this.button(latest, this.tr("Go to bottom of chat", "到對話底部"), () => { scrolling.scrollTop = scrolling.scrollHeight; latest.classList.add("is-hidden"); }); scrolling.addEventListener("scroll", () => { this.scrollEpoch++; latest.classList.toggle("is-hidden", scrolling.scrollHeight - scrolling.scrollTop - scrolling.clientHeight < 100); });
    const composer = chatPanel.createDiv("ct-composer"); if (engine.session.status === "completed") { this.button(composer, this.tr("Continue chatting", "繼續聊"), async () => { if (engine.session.id.startsWith("sample-")) await this.copySample(); const current = this.engine; if (current) await this.plugin.confirmAiUsage(current.session.model, () => current.continueTable()); }).addClass("mod-cta"); const question = composer.createEl("textarea", { attr: { rows: "2", maxlength: "1800", placeholder: this.tr("Ask the table a follow-up…", "追問桌上的人…"), "aria-label": this.tr("Follow-up question", "追問"), "data-ct-field": "follow-up" } }); question.value = this.composerValues.get("follow-up") ?? this.composerValues.get("intervention-text") ?? ""; question.addEventListener("input", () => this.composerValues.set("follow-up",question.value)); this.button(composer, this.tr("Ask", "送出追問"), async () => { const value = question.value.trim(); if (!value) return; question.value = ""; this.composerValues.delete("follow-up"); this.composerValues.delete("intervention-text"); if (engine.session.id.startsWith("sample-")) await this.copySample(); if (this.engine) await this.plugin.confirmAiUsage(this.engine.session.model, () => this.engine!.ask(value)); }, engine.busy).addClass("mod-cta"); if (engine.session.dirtyNotes) { this.button(composer, this.tr("Refresh observer notes", "更新觀察者整理"), async () => { await this.plugin.confirmAiUsage(engine.session.model, () => engine.refreshObserverNotes()); }, engine.busy || engine.persistenceFailed); composer.createEl("small", { cls: "ct-muted", text: this.tr("Uses the whole table and saved drafts; it does not add dialogue.", "依整桌對談與已保存草稿整理，不會新增發言。") }); } }
    else if (engine.session.status === "ready") this.button(composer, this.tr("Generate conversation", "開始生成對談"), async () => { await this.plugin.confirmAiUsage(engine.session.model, () => engine.start()); }).addClass("mod-cta");
    else if (engine.session.status === "error") { if (!engine.persistenceFailed) this.button(composer, this.tr(engine.session.draftMarkdown ? "Continue generating from saved draft" : "Retry this segment", engine.session.draftMarkdown ? "從已保存草稿繼續生成" : "重試這一段"), async () => { await this.plugin.confirmAiUsage(engine.session.model, () => engine.start()); }); else this.button(composer, this.tr("Retry saving", "重試保存"), () => engine.retrySave()); if (!engine.persistenceFailed && (engine.session.draftMarkdown || engine.session.transcriptMarkdown || engine.session.questions.length)) { this.button(composer, this.tr("Refresh observer notes only", "只整理目前內容"), async () => { await this.plugin.confirmAiUsage(engine.session.model, () => engine.refreshObserverNotes()); }, engine.busy); composer.createEl("small", { cls: "ct-muted", text: this.tr("Uses saved dialogue and drafts without adding new speaker turns.", "根據已保存對談與草稿整理，不會新增來賓發言。") }); } this.button(composer, this.tr("Edit settings and start another", "調整設定，再開一桌"), () => this.home(engine.session)); this.button(composer, this.tr("Open Markdown", "開啟 Markdown"), async () => { const file = await this.store.openMarkdown(engine.session.id); await this.app.workspace.getLeaf(false).openFile(file); }); if (engine.session.draftMarkdown) this.button(composer, this.tr("Copy draft", "複製草稿"), async () => { await navigator.clipboard.writeText(engine.session.draftMarkdown ?? ""); new Notice(this.tr("Draft copied.", "草稿已複製。")); }); const savedDraft = !engine.persistenceFailed && !!engine.session.draftMarkdown; const message = composer.createEl("p", { cls: "ct-error", text: `${engine.error || engine.session.error || this.tr("Generation stopped.", "生成已停止。")} · ${engine.persistenceFailed ? this.tr("The latest text is only in this open view. Retry saving or copy the draft.", "最新內容尚未保存，只保留在目前畫面；請重試保存或複製草稿。") : savedDraft ? this.tr("Received text is saved as a draft.", "已收到的文字已保存為草稿。") : this.tr("The existing conversation is preserved.", "原有對談內容已保留。")}` }); void message; if (this.composerValues.get("intervention-text")) { composer.createEl("p", { cls: "ct-muted", text: this.tr("Your unsent message is kept below.", "尚未送出的訊息保留在下方。") }); const retained = composer.createEl("textarea", { attr: { rows: "2", placeholder: this.tr("Unsent message","尚未送出的訊息"), "data-ct-field": "intervention-text" } }); retained.value = this.composerValues.get("intervention-text") ?? ""; retained.addEventListener("input", () => this.composerValues.set("intervention-text",retained.value)); } }
    else if (engine.busy) { const select = composer.createEl("select", { attr: { "aria-label": this.tr("How to join", "介入方式"), "data-ct-field": "intervention-kind" } }); for (const [value,en,zh] of [["comment","Say something","說點什麼"],["guest-question","Ask a guest","追問某人"],["redirect","Change direction","換個方向"]]) select.createEl("option", { value, text: this.tr(en,zh) }); select.value = this.composerValues.get("intervention-kind") ?? "comment"; select.addEventListener("change", () => this.composerValues.set("intervention-kind",select.value)); const target = composer.createEl("input", { attr: { type: "text", placeholder: this.tr("Guest name (optional)","來賓姓名（選填）"), "data-ct-field": "intervention-target" } }); target.value = this.composerValues.get("intervention-target") ?? ""; target.addEventListener("input", () => this.composerValues.set("intervention-target",target.value)); const input = composer.createEl("textarea", { attr: { rows: "2", placeholder: this.tr("Join the conversation…","加入對談…"), "data-ct-field": "intervention-text" } }); input.value = this.composerValues.get("intervention-text") ?? ""; input.addEventListener("input", () => this.composerValues.set("intervention-text",input.value)); this.button(composer, this.tr("Send","送出"), async () => { if (!input.value.trim()) return; const text = input.value; input.value = ""; this.composerValues.delete("intervention-text"); try { await engine.intervene(select.value as "comment"|"guest-question"|"redirect",text,target.value); } catch (error) { input.value = text; this.composerValues.set("intervention-text",text); throw error; } }); }
    if (/changed outside|外部修改|outside this room/i.test(engine.error)) this.button(composer, this.tr("Reload edits", "重新載入修改"), async () => { if (engine.busy) await engine.stop(); const session = await this.store.reload(this.store.sessionPath(engine.session.id)); this.plugin.coffeeManager?.forget(engine.session.id); this.attach(session); });
    const insight = body.createDiv("ct-insight-panel"); insight.createEl("h3", { text: this.tr("Observer’s notes", "觀察者整理") }); const notes = engine.session.observerNotes ?? []; if (engine.session.dirtyNotes) insight.createEl("p", { cls: "ct-muted", text: this.tr("The conversation changed; these notes have not been refreshed yet.", "對談內容已修改，這份整理尚未更新。") });
    if (notes[0]) this.renderMarkdown(notes[0], insight.createDiv("ct-insight-latest markdown-rendered")); else insight.createEl("p", { cls: "ct-muted", text: this.tr("The observer’s notes will appear when this segment finishes.", "本段完成後會更新觀察者整理。") });
    if (engine.session.observerDraftMarkdown || (engine.busy && engine.session.dirtyNotes)) { insight.createEl("p", { cls: "ct-muted", text: this.tr("Updating notes from the saved conversation…", "正在根據已保存對談更新整理…") }); const draft = insight.createDiv("ct-observer-draft"); if (engine.session.observerDraftMarkdown) this.renderStreaming(engine.session.observerDraftMarkdown, draft); }
    if (notes.length > 1) { const history = insight.createEl("details"); history.createEl("summary", { text: this.tr("Earlier notes", "先前整理") }); for (const [index,note] of notes.slice(1).entries()) { history.createEl("h4", { text: this.tr(`Version ${notes.length-index-1}`,`第 ${notes.length-index-1} 版`) }); this.renderMarkdown(note, history.createDiv("ct-insight-history markdown-rendered")); } }
    if (engine.session.status === "completed" && !engine.session.id.startsWith("sample-")) { const handoff = this.button(insight, this.tr("Take to VAM for deeper research", "帶去 VAM 深入研究"), () => this.plugin.openCoffeeHandoff(engine.session, this.store.sessionPath(engine.session.id))); handoff.addClass("mod-cta"); }
    if (engine.session.status === "completed") this.button(insight, this.tr("Edit settings and start another table", "編輯設定，再開一桌"), () => this.returnHome(engine.session));
    this.renderRoster(roster, liveRosterFor(engine.session, draft)); this.updateStatus(status, engine); this.stateSignature = `${engine.session.status}:${engine.busy}:${engine.error}:${engine.session.questions.length}`; this.contentEl.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("[data-ct-field]").forEach(field => { const value = this.composerValues.get(field.dataset.ctField!); if (value !== undefined && !field.value) field.value = value; }); if (activeField) { const field = activeField === "intervention-text" && engine.session.status === "completed" ? "follow-up" : activeField, replacement = this.contentEl.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[data-ct-field="${field}"]`); if (replacement) { if (activeValue !== undefined) replacement.value = activeValue; replacement.focus(); if (!(replacement instanceof HTMLSelectElement)) { try { replacement.setSelectionRange(activeStart ?? replacement.value.length, activeEnd ?? replacement.value.length); } catch { /* Browser may not support selection for this control. */ } } } }
    if (engine.busy && this.statusTimer === null && typeof window.setInterval === "function") this.statusTimer = window.setInterval(() => { const current = this.contentEl.querySelector<HTMLElement>(".ct-status"); if (current && this.engine) this.updateStatus(current,this.engine); },1000); if (!engine.busy && this.statusTimer !== null) { window.clearInterval(this.statusTimer); this.statusTimer = null; }
    const markdownJobs = this.markdownJobs; this.markdownJobs = null; const sessionId = engine.session.id; void Promise.all(markdownJobs ?? []).then(() => new Promise<void>(resolve => window.requestAnimationFrame(() => { if (this.closed || this.engine?.session.id !== sessionId || this.scrollEpoch !== scrollEpoch) { resolve(); return; } if (firstScroll === "top") scrolling.scrollTop = 0; else if (firstScroll === "bottom" || (hadPriorScroll && wasBottom)) scrolling.scrollTop = scrolling.scrollHeight; else scrolling.scrollTop = oldTop; resolve(); }))); if (hadPriorScroll && !wasBottom) scrolling.scrollTop = oldTop;
  }
  private renderBubbles(markdown: string, target: HTMLElement): void { const speeches = parseSpeeches(markdown); if (!speeches.length) { this.renderMarkdown(markdown,target); return; } for (const item of speeches) this.renderSpeech(item.name,item.role,item.text,target); }
  private renderRound(markdown: string, roundId: string | undefined, target: HTMLElement): void { const speeches = parseSpeeches(markdown), interventions = (this.engine?.session.interventions ?? []).filter(item => item.roundId && item.roundId === roundId).sort((a,b) => (a.afterTurn ?? 0) - (b.afterTurn ?? 0)); if (!speeches.length) { if (markdown) this.renderMarkdown(markdown,target.createDiv("ct-live-plain markdown-rendered")); for (const item of interventions) this.renderUserBubble(item.text,target); return; } let next = 0; for (let index = 0; index <= speeches.length; index++) { while (next < interventions.length && (interventions[next].afterTurn ?? 0) <= index) this.renderUserBubble(interventions[next++].text,target); if (index < speeches.length) { const speech = speeches[index]; this.renderSpeech(speech.name,speech.role,speech.text,target); } } }
  private renderSpeech(name: string, role: string, text: string, target: HTMLElement): void { if (name === "你" || name.toLowerCase() === "you") { this.renderUserBubble(text,target); return; } const article = target.createDiv("ct-message"); article.createDiv({ cls: `ct-avatar ct-color-${avatarColor(name)}`, text: initials(name), attr: { "aria-hidden": "true" } }); const content = article.createDiv("ct-message-content"); content.createEl("strong", { text: name }); content.createSpan({ cls: "ct-role", text: role }); this.renderMarkdown(text,content.createDiv("ct-bubble markdown-rendered")); }
  private renderStreaming(markdown: string, target: HTMLElement): void { const speeches = parseSpeeches(markdown); if (!speeches.length) { this.renderMarkdown(markdown,target.createDiv("ct-live-plain markdown-rendered")); return; } this.renderBubbles(markdown,target); }
  private renderUserBubble(text: string, target: HTMLElement): void { const article = target.createDiv("ct-message ct-message-user"); article.createDiv({ cls: "ct-avatar ct-user-avatar", text: this.tr("You","你") }); const content = article.createDiv("ct-message-content"); content.createEl("strong", { text: this.tr("You","你") }); this.renderMarkdown(text,content.createDiv("ct-bubble markdown-rendered")); }
  private renderMarkdown(markdown: string, target: HTMLElement): void { const job = MarkdownRenderer.render(this.app,markdown,target,this.store.sessionPath(this.engine?.session.id ?? ""),this).then(() => undefined); this.markdownJobs?.push(job); }
  private renderRoster(target: HTMLElement, people: Array<{name:string;role:string;bio:string}>): void { target.empty(); for (const person of people) { const chip = target.createEl("button", { cls: "ct-person", attr: { title: person.bio, "aria-label": `${person.name}, ${person.role}. ${person.bio}` } }); chip.createSpan({ cls: `ct-avatar ct-color-${avatarColor(person.name)}`, text: initials(person.name), attr: { "aria-hidden": "true" } }); chip.createSpan({ cls: "ct-person-label", text: `${person.name} · ${person.role}` }); chip.addEventListener("click", () => new Notice(`${person.name}｜${person.role}\n${person.bio}`)); } }
  private updateStatus(status: HTMLElement, engine: CoffeeEngine): void { const elapsed = engine.busy ? `${Math.floor((Date.now()-engine.startedAt)/60000)} min` : ""; const last = parseSpeeches(engine.session.draftMarkdown ?? "").at(-1); status.setText(engine.error || (engine.busy ? `${last ? `${last.name} · ` : ""}${this.tr("is speaking","正在發言")} · ${elapsed}` : engine.session.status === "completed" ? this.tr("Table complete","對談完成") : engine.session.status === "error" ? this.tr("Stopped · draft saved","已停止 · 草稿已保存") : this.tr("Ready to generate","準備生成"))); }
  private async copySample(): Promise<void> { const source = this.engine?.session; if (!source || !source.id.startsWith("sample-")) return; const copy = createSession(source.topic,this.plugin.settings.cliModel,this.plugin.settings.cliReasoning,source.language,source.guests); copy.status="completed"; copy.transcriptMarkdown=source.transcriptMarkdown; copy.rounds=source.rounds?.map(item=>({...item})) ?? []; copy.observerNotes=[...(source.observerNotes ?? [])]; copy.questions=source.questions.map(item=>({...item,id:crypto.randomUUID()})); await this.store.save(copy); this.attach(copy); }
  private refresh(): void { const engine = this.engine; if (!engine || this.closed) return; if (engine.deleted) { this.returnHome(); return; } const signature = `${engine.session.status}:${engine.busy}:${engine.error}:${engine.session.questions.length}`; if (signature !== this.stateSignature) { this.render(); return; } if (this.renderTimer !== null) return; this.renderTimer = window.setTimeout(() => { this.renderTimer = null; if (!this.engine || this.closed) return; this.refreshLive(); },250); }
  private refreshLive(): void { const engine = this.engine; if (!engine) return; const scroller = this.contentEl.querySelector<HTMLElement>(".ct-chat-scroll"), wasBottom = !scroller || scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight < 100, oldTop = scroller?.scrollTop ?? 0; const status = this.contentEl.querySelector<HTMLElement>(".ct-status"); if (status) this.updateStatus(status,engine); const draft = this.contentEl.querySelector<HTMLElement>(".ct-live-draft"); if (draft) { draft.empty(); const round = [...(engine.session.rounds ?? [])].reverse().find(item => item.status === "generating"); if (engine.session.status !== "completed" && engine.session.draftMarkdown) this.renderRound(engine.session.draftMarkdown,round?.id,draft); } for (const question of engine.session.questions) { const live = this.contentEl.querySelector<HTMLElement>(`[data-live-question-id="${question.id}"]`); if (live) { live.empty(); if (question.draftAnswer) this.renderStreaming(question.draftAnswer,live); } } const roster = this.contentEl.querySelector<HTMLElement>(".ct-roster"); if (roster) this.renderRoster(roster, liveRosterFor(engine.session, engine.session.draftMarkdown ?? "")); const observerDraft = this.contentEl.querySelector<HTMLElement>(".ct-observer-draft"); if (observerDraft) { observerDraft.empty(); if (engine.session.observerDraftMarkdown) this.renderStreaming(engine.session.observerDraftMarkdown, observerDraft); } if (scroller) scroller.scrollTop = wasBottom ? scroller.scrollHeight : oldTop; }
}
function observerNotes(markdown: string): string { return markdown.match(/^# (?:觀察者整理|Observer(?:[’']s)? notes)[\s\S]*$/m)?.[0] ?? ""; }
function initials(name: string): string { return [...name.replace(/[^\p{L}\p{N}]/gu,"")].slice(0,2).join("") || "•"; }
function avatarColor(name: string): number { let hash=0; for (const char of name) hash=(hash*31+char.codePointAt(0)!)|0; return Math.abs(hash)%8; }
